//
//  BaseWireframe.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 21.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

enum WireframeTransitionType {
    case root
    case present(fromViewController: UIViewController)
    case push(navigationController: UINavigationController, animated: Bool = true)
}

class BaseWireframe {
    
    internal func changeView(transationType: WireframeTransitionType, viewController: UIViewController) {
        switch transationType {
        case .root:
            UIApplication.shared.windows.first?.rootViewController = viewController
            UIApplication.shared.windows.first?.makeKeyAndVisible()
        case .present(let fromViewController):
            fromViewController.present(viewController, animated: true, completion: nil)
        case .push(let navigationController, let animated):
            navigationController.pushViewController(viewController, animated: animated)
        }
    }
}
