//
//  DetailProtocols.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 22.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol DetailViewControllerProtocol: BaseViewControllerProtocol {
    
    func showMovieDetail(movieDetail: MovieDetail)
}

// MARK: - Presenter

protocol DetailPresenterViewProtocol: BasePresenterViewProtocol {
    
    func fetchData()
}

protocol DetailPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func showMovieDetail(movieDetail: MovieDetail)
}

protocol DetailPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol DetailInteractorProtocol: BaseInteractorProtocol {
    
    func fetchData(imdbID: String)
    func logData(movie: Movie)
}
