//
//  DetailViewController.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 22.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit
import SkeletonView

class DetailViewController: BaseViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var posterImageView: UIImageView!
    @IBOutlet weak var typeLabel: UILabel!
    @IBOutlet weak var yearLabel: UILabel!
    @IBOutlet weak var actorsStackView: UIStackView!
    @IBOutlet weak var actorsLabel: UILabel!
    @IBOutlet weak var genreStackView: UIStackView!
    @IBOutlet weak var genreLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var imdbStackView: UIStackView!
    @IBOutlet weak var imdbRatingLabel: UILabel!
    
    // MARK: - Dependencies
    
    var presenter: DetailPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.fetchData()
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
        barTitle = "detail_view_controller.title".localized
        
        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .close, target: self, action: #selector(dismissButtonTapped))
        
        imdbStackView.skeletonCornerRadius = 4.0
        genreStackView.skeletonCornerRadius = 4.0
        actorsStackView.skeletonCornerRadius = 12.0
        descriptionLabel.lastLineFillPercent = 100
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
    @objc func dismissButtonTapped() {
        dismiss(animated: true, completion: nil)
    }
    
}

// MARK: - Extensions

// MARK: - Protocol Implemantations

extension DetailViewController: DetailViewControllerProtocol {
    
    func showMovieDetail(movieDetail: MovieDetail) {
        
        self.titleLabel.text = movieDetail.title
        self.posterImageView.setImage(url: movieDetail.poster) { (result) in
            self.posterImageView.hideSkeleton()
            self.posterImageView.cornerRadiusV = 12.0
        }
        self.typeLabel.text = movieDetail.type.capitalizingFirstLetter()
        self.yearLabel.text = movieDetail.year
        self.actorsLabel.text = movieDetail.actors
        self.genreLabel.text = movieDetail.genre
        self.descriptionLabel.text = movieDetail.plot
        self.imdbRatingLabel.text = movieDetail.imdbRating
    }
    
    override func startProgress() {
        
        titleLabel.showAnimatedSkeleton()
        posterImageView.showAnimatedSkeleton()
        typeLabel.showAnimatedSkeleton()
        yearLabel.showAnimatedSkeleton()
        actorsStackView.showAnimatedSkeleton()
        genreStackView.showAnimatedSkeleton()
        descriptionLabel.showAnimatedSkeleton()
        imdbStackView.showAnimatedSkeleton()
    }
    
    override func stopProgress() {
        
        titleLabel.hideSkeleton()
        typeLabel.hideSkeleton()
        yearLabel.hideSkeleton()
        actorsStackView.hideSkeleton()
        genreStackView.hideSkeleton()
        descriptionLabel.hideSkeleton()
        imdbStackView.hideSkeleton()
    }
}
