//
//  HomeProtocols.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 22.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol HomeViewControllerProtocol: BaseViewControllerProtocol {
    
    func showSearchResult(_ messageType: MessageType, _ result: [Movie])
}

// MARK: - Presenter

protocol HomePresenterViewProtocol: BasePresenterViewProtocol {
    
    func searchMovies(_ searchText: String)
}

protocol HomePresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func handleSearchResult(_ result: [Movie])
}

protocol HomePresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol HomeInteractorProtocol: BaseInteractorProtocol {
    
    func fetchMovies(_ searchText: String)
}
