//
//  HomeWireframe.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 22.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import UIKit

class HomeWireframe: BaseWireframe {
    
    // TODO: Use tuples for extras if you have more than once parameters
    func show(transitionType: WireframeTransitionType, delegate: HomePresenterDelegateProtocol? = nil, extras: Any? = nil) {
        // TODO: Choose related storyboard
        let viewController: HomeViewController = UIStoryboard.Main.instantiateViewController()
        
        // TODO: Inteactor Dependencies
        let interactor = HomeInteractor(networkService: NetworkService.sharedInstance, firebaseService: FirebaseService.sharedInstance)
        
        let presenter = HomePresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        let navigationController = UINavigationController(rootViewController: viewController)
        
        changeView(transationType: transitionType, viewController: navigationController)
    }
    
}
