//
//  SplashViewController.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 21.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim
//

import UIKit

class SplashViewController: BaseViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var launchText: UILabel!
    
    // MARK: - Dependencies
    
    var presenter: SplashPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.checkNetworkState()
//        presenter.getLaunchText()
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
}

// MARK: - Extensions

// MARK: - Protocol Implemantations

extension SplashViewController: SplashViewControllerProtocol {
    
}
