//
//  SplashInteractor.swift
//  Movies
//
//  Created by Burak Çokyıldırım on 21.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Burak Cokyildirim

import Foundation

class SplashInteractor: BaseInteractor {
    
    // MARK: - Dependencies
    
    var presenter: SplashPresenterInteractorProtocol!
    
    // MARK: - Initialization
    
    override init(networkService: NetworkService? = nil, firebaseService: FirebaseService? = nil) {
        super.init(networkService: networkService, firebaseService: firebaseService)
    }
    
    // MARK: - Business Logic

}

// MARK: - Extensions

// MARK: - Protocols Implemantations

extension SplashInteractor: SplashInteractorProtocol {
    
    func checkNetworkState() {
        
        if !networkService.isInternetAvailable() {
            presenter.showNetworkError()
        }
    }
    
    func fetchLaunchText() {
        
//        firebaseService
    }
}
